# This is a basic workflow to help you get started with Actions
name: Lint Workflow
on:
  pull_request:
    branches:
      - master
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Up SDK
        uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Looking for gradle check
        run: ./gradlew

      - name: Run ktlintCheck
        run: ./gradlew ktlintCheck

      - name: Run ktlintFormat
        run: ./gradlew ktlintFormat